### ISSUE TITLE
The Linux PC is required to be connected to Windows PC using LAN?

### ISSUE THREAD

**Issue by andiconda** [ravijo/kinect_anywhere#2]
Do I need to check the Ip of two computer and ping them?

**Comment by ravijo** [comment]
@alexchauncy: Yes, please. Basically, the Kinect data is being acquired at Windows PC. It is transferred to Linux PC using TCP sockets. Since the amount of data is huge, using Ethernet LAN is preferred.

Anyways, you need to make sure that Linux and Windows PC are able to communicate through Ethernet LAN. Here are two things to keep in mind while connecting through ethernet, which can make it quicker-
* You may need to assign manual IP to both the machines in a proper range
* You may need to bypass or turn off the firewall. Especially in Windows PC, it blocks TCP request.

Hope it helps! Let me know if there are more issues!

**Comment by andiconda** [comment]
Thank you. It helps.
